unit LeveledListLimits;
// Only use the disposable fixtures generated by leveled_list_limits.py.
// Load Limits1/254/255/256/257.esm and Unbounded.esm with their synthetic master.
var Report: TStringList;

procedure Note(S: string);
begin
  Report.Add(S);
  Report.SaveToFile('limits-results.txt');
  AddMessage(S);
end;

procedure Require(B: Boolean; S: string);
begin
  if not B then raise Exception.Create('FAIL: ' + S);
  Note('PASS: ' + S);
end;

function ListRecord(N: Integer): IInterface;
var F: IInterface;
begin
  F := FileByName('Limits' + IntToStr(N) + '.esm');
  if not Assigned(F) then raise Exception.Create('Missing limit fixture');
  Result := ElementByIndex(GroupBySignature(F, 'LVLI'), 0);
end;

function Entries(R: IInterface): IInterface;
begin
  Result := ElementByPath(R, 'Leveled List Entries');
end;

procedure RejectAppend(R: IInterface);
var A, E: IInterface; CountBefore: Integer; StoredBefore: string;
begin
  A := Entries(R);
  CountBefore := ElementCount(A);
  StoredBefore := GetElementEditValues(R, 'LLCT');
  try
    E := ElementAssign(A, HighInteger, ElementByIndex(A, 0), False);
  except on Ex: Exception do Note('REJECTED: ' + Ex.Message); end;
  Require(ElementCount(A) = CountBefore, 'append leaves entries unchanged');
  Require(GetElementEditValues(R, 'LLCT') = StoredBefore, 'append leaves count unchanged');
end;

procedure Run;
var R, A, E, Target, Source: IInterface; Stream: TFileStream; N: Integer;
begin
  R := ListRecord(254);
  A := Entries(R);
  E := ElementAssign(A, HighInteger, ElementByIndex(A, 0), False);
  Require(ElementCount(A) = 255, '254 to 255 allowed');
  Require(GetElementEditValues(R, 'LLCT') = '255', '255 stored without overflow');
  Require(Check(A) = '', '255 entries check clean');
  RejectAppend(R);
  R := ListRecord(255);
  RejectAppend(R);
  for N := 256 to 257 do begin
    R := ListRecord(N);
    Require(ElementCount(Entries(R)) = N, 'oversized input is not truncated');
    Require(Pos('maximum of 255', Check(Entries(R))) > 0, 'oversized input diagnosed');
  end;
  Target := ListRecord(1);
  Source := ListRecord(256);
  try
    E := ElementAssign(Entries(Target), LowInteger, Entries(Source), False);
  except on Ex: Exception do Note('REJECTED: ' + Ex.Message); end;
  Require(ElementCount(Entries(Target)) = 1, 'rejected array replacement preserves target');
  Require(GetElementEditValues(Target, 'LLCT') = '1', 'rejected replacement preserves count');
  E := ElementAssign(Entries(Target), LowInteger, Entries(ListRecord(255)), False);
  Require(ElementCount(Entries(Target)) = 255, 'valid whole-array replacement allowed');
  R := ListRecord(257);
  A := Entries(R);
  RemoveElement(A, ElementByIndex(A, ElementCount(A) - 1));
  Require(ElementCount(A) = 256, 'oversized input can be reduced');
  Require(GetElementEditValues(R, 'LLCT') = '1', 'remaining invalid count is not wrapped again');
  RemoveElement(A, ElementByIndex(A, ElementCount(A) - 1));
  Require(ElementCount(A) = 255, 'oversized input can be repaired');
  Require(GetElementEditValues(R, 'LLCT') = '255', 'repaired count synchronized');
  Require(Check(A) = '', 'repaired array checks clean');
  Stream := TFileStream.Create('limits-repaired.esm', fmCreate);
  try FileWriteToStream(GetFile(R), Stream, 0); finally Stream.Free; end;
  R := ElementByIndex(GroupBySignature(FileByName('Unbounded.esm'), 'FLST'), 0);
  A := ElementByPath(R, 'FormIDs');
  Require(ElementCount(A) = 300, 'unbounded form list retains 300 entries');
  E := ElementAssign(A, HighInteger, ElementByIndex(A, 0), False);
  Require(ElementCount(A) = 301, 'unbounded form list can grow');
end;

function Initialize: Integer;
begin
  Report := TStringList.Create;
  try
    try Run; Note('COMPLETE');
    except on E: Exception do Note('HARNESS_ERROR: ' + E.Message); end;
  finally Report.Free; end;
  Result := 0;
end;
end.
